name: Docker Series CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: docker build csharp
      run: |
        docker build ./c# -t mikeybabs/csharp:1.0.0
    - name: docker build nodejs
      run: |
        docker build ./nodejs -t mikeybabs/nodejs:1.0.0
    - name: docker build python
      run: |
        docker build ./python -t mikeybabs/python:1.0.0
    - name: docker build golang
      run: |
        docker build ./golang -t mikeybabs/golang:1.0.0
